language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli
  - npm link @angular/cli
  - npm install -g @angular-devkit/build-angular
  - npm install -g tslint typescript
  - npm install -g yarn

script:
  - yarn lint
  - yarn build --base-href https://ebadmail.github.io/Angular-REST-API-back-end/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/Angular-REST-API-back-end
  on:
    branch: master
